import Testing
@testable import AdventOfCode2025

struct Day7Tests {

    @Test(
        arguments: [day7DummyCase, day7DummyCase2, day7DummyCase3, day7TestCase]
        )
    func challenge7(testCase: AdventTestCase) {

        let day7 = Day7(input: testCase.input)
        let result1 = day7.findNoOfSplits()
        #expect(result1 == testCase.answer1)
        let result2 = day7.findAlternateTimelines()
        #expect(result2 == testCase.answer2)

    }

}

let day7DummyCase: AdventTestCase = .init(input: """
    ..S.
    ....
    ..^.
    .^..
    ....
    """, answer1: 2, answer2: 3)

let day7DummyCase2: AdventTestCase = .init(input: """
    ..S..
    .....
    ..^..
    .^.^.
    ^.^.^
    .....
    """, answer1: 6, answer2: 6)

let day7DummyCase3: AdventTestCase = .init(input: """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """, answer1: 21, answer2: 40)
